=== TanishaShrotriya96/TE/WTLab/XML2/info.xsd
<?xml version ="1.0"?>
<xs:schema xmlns:xs="https://www.w3.org/2001/XMLSchema">
        <xs:element name="CLIENTS" minOccurs="1"/>
	<xs:element name="CLIENT" type="Cl" minOccurs="1"/>
	<xs:complexType name="Cl" >
	<xs:sequence>
		<xs:element name="NAME" type="xsd:string"  minOccurs="1" maxOccurs="1"/>	
		<xs:element name="OCCUPATION" type="xsd:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="HOBBIES" type="Hb"  minOccurs="1" maxOccurs="1"/>
		<xs:complexType name="Hb">
		<xs:sequence >
			<xs:element name="HOBBY" type="Val" minOccurs="1"/>
			<xs:complexType name="VAl">
		        <xs:sequence >
			     <xs:element name="VALUE" type="xsd:string" minOccurs="1" maxOccurs="1"/>
		        </xs:sequence>
		        </xs:complexType>
		</xs:sequence>
		</xs:complexType>
	</xs:sequence>
	</xs:complexType>
</xs:schema>

=== TanishaShrotriya96/TE/XML2/info.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="info.xsl"?>
<CLIENTS xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="info.xsd">
<CLIENT>
<NAME>Tanisha</NAME>
<OCCUPATION>Engineer</OCCUPATION>
<HOBBIES>
<HOBBY>
 <VALUE>Music</VALUE>
</HOBBY>
<HOBBY>
 <VALUE>Sketching</VALUE>
</HOBBY>
<HOBBY>
 <VALUE>Dancing</VALUE>
</HOBBY>
</HOBBIES>
</CLIENT>

<CLIENT>
<NAME>Shubhangi</NAME>
<OCCUPATION>Engineer</OCCUPATION>
<HOBBIES>
<HOBBY>
 <VALUE>Music</VALUE>
</HOBBY>
<HOBBY>
 <VALUE>Cooking</VALUE>
</HOBBY>
</HOBBIES>
</CLIENT>

<CLIENT>
<NAME>Pooja</NAME>
<OCCUPATION>Dancer</OCCUPATION>
<HOBBIES>
<HOBBY>
 <VALUE>Dance</VALUE>
</HOBBY>
<HOBBY>
 <VALUE>Music</VALUE>
</HOBBY>
<HOBBY>
 <VALUE>Math</VALUE>
</HOBBY>
</HOBBIES>
</CLIENT>
</CLIENTS>
